name: Build Android APK

on:
  push:
    branches:
      - main # یا master، بسته به نام شاخه اصلی شما
  workflow_dispatch: # برای اجرای دستی پایپ‌لاین در گیت‌هاب

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # نسخه مناسب برای گریدل‌های جدید فلاتر

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # می‌توانید نسخه دقیق فلاتر را هم اینجا مشخص کنید، مثلاً: flutter-version: '3.22.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk